task_manager/labels/urls.py
from django.urls import path
from task_manager.labels import views


app_name = "labels"
urlpatterns = [
    path('', views.LabelListView.as_view(), name='index'),
    path('create/', views.LabelCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.LabelUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.LabelDeleteView.as_view(), name='delete'),
]

task_manager/statuses/urls.py
from django.urls import path
from task_manager.statuses import views


app_name = "statuses"
urlpatterns = [
    path('', views.StatusListView.as_view(), name='index'),
    path('create/', views.StatusCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.StatusUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.StatusDeleteView.as_view(), name='delete'),
]

task_manager/tasks/urls.py
from django.urls import path
from task_manager.tasks import views


app_name = "tasks"
urlpatterns = [
    path('', views.TaskListView.as_view(), name='index'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
    path('<int:pk>/', views.TaskDetailView.as_view(), name='detail'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import path, include

from task_manager import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('admin/', admin.site.urls),
]

task_manager/users/urls.py
from django.urls import path
from task_manager.users import views


app_name = "users"
urlpatterns = [
    path('', views.UserListView.as_view(), name='index'),
    path('create/', views.SignUp.as_view(), name='signup'),
    path('<int:pk>/update/', views.UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='delete'),
]

task_manager/labels/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.db.models import ProtectedError


class Label(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def delete(self, *args, **kwargs):
        if self.task_set.exists():
            raise ProtectedError(
                _("Cannot delete label because they are being used"),
                self
            )
        super().delete(*args, **kwargs)

task_manager/statuses/models.py
from django.db import models


class Status(models.Model):
    name = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/tasks/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from task_manager.users.models import User
from task_manager.statuses.models import Status
from task_manager.labels.models import Label


class Task(models.Model):
    name = models.CharField(
        max_length=100,
        unique=True,
        blank=False,
        verbose_name=_('Name'),
    )
    description = models.TextField(
        max_length=300,
        blank=True,
        verbose_name=_('Description'),
    )
    author = models.ForeignKey(User,
                               on_delete=models.PROTECT,
                               verbose_name=_('Author'),
                               related_name='author',
                               )
    executor = models.ForeignKey(User,
                                 blank=True,
                                 null=True,
                                 on_delete=models.PROTECT,
                                 verbose_name=_('Executor'),
                                 related_name='executor',
                                 )
    status = models.ForeignKey(Status,
                               on_delete=models.PROTECT,
                               verbose_name=_('Status'),
                               )
    labels = models.ManyToManyField(Label,
                                   blank=True,
                                   )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/users/models.py
from django.contrib.auth.models import AbstractUser


# Create your models here.
class User(AbstractUser):

    def __str__(self):
        return self.get_full_name()

task_manager/labels/forms.py
from django import forms
from task_manager.labels.models import Label


class LabelForm(forms.ModelForm):
    class Meta:
        model = Label
        fields = (
            'name',
        )

task_manager/tasks/forms.py
from django import forms
from task_manager.tasks.models import Task


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = (
            'name',
            'description',
            'executor',
            'status',
            'labels',
        )

task_manager/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from task_manager.users.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'password1',
            'password2'
        )

task_manager/labels/views.py
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from django.views.generic import ListView

from task_manager.labels.forms import LabelForm
from task_manager.labels.models import Label

from task_manager.mixins import CustomLoginMixin
from task_manager.views import (CustomCreateView,
                               CustomUpdateView,
                               CustomDeleteView)


class LabelListView(CustomLoginMixin, ListView):
    model = Label
    template_name = 'labels/index.html'
    context_object_name = 'labels'

class LabelCreateView(CustomCreateView):
    model = Label
    form_class = LabelForm
    success_url = reverse_lazy('labels:index')
    success_message = _("Label successfully created")
    extra_context = {
        "button_name": _("Create"),
        "header": _("Create a label")
    }

class LabelUpdateView(CustomUpdateView):
    model = Label
    form_class = LabelForm
    success_url = reverse_lazy('labels:index')
    success_message = _("The label successfully updated")
    extra_context = {
        "button_name": _("Update"),
        "header": _("Update label")
    }

class LabelDeleteView(CustomDeleteView):
    model = Label
    success_url = reverse_lazy('labels:index')
    success_message = _('Label successfully deleted')
    protected_message = _("Cannot delete a label because it is in use")
    protected_url = reverse_lazy('labels:index')
    context_object_name = 'label'
    extra_context = {
        "title": _("Label deletion"),
        "confirmation": _("Are you sure you want to delete the label")
    }

task_manager/statuses/views.py
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from django.views.generic import ListView

from task_manager.statuses.forms import StatusForm
from task_manager.statuses.models import Status
from task_manager.views import (CustomCreateView,
                               CustomUpdateView,
                               CustomDeleteView)
from task_manager.mixins import CustomLoginMixin


class StatusListView(CustomLoginMixin, ListView):
    model = Status
    template_name = 'statuses/index.html'
    context_object_name = 'statuses'

class StatusCreateView(CustomCreateView):
    model = Status
    form_class = StatusForm
    success_url = reverse_lazy('statuses:index')
    success_message = _("Status successfully created")
    extra_context = {
        "button_name": _("Create"),
        "header": _("Create a status")
    }

class StatusUpdateView(CustomUpdateView):
    model = Status
    form_class = StatusForm
    success_url = reverse_lazy('statuses:index')
    success_message = _("The status successfully updated")
    context_object_name = 'status'
    extra_context = {
        "button_name": _("Update"),
        "header": _("Update status")
    }

class StatusDeleteView(CustomDeleteView):
    model = Status
    success_url = reverse_lazy('statuses:index')
    success_message = _('Status successfully deleted')
    protected_message = _("Cannot delete a status because it is in use")
    protected_url = reverse_lazy('statuses:index')
    extra_context = {
        "title": _("Status deletion"),
        "confirmation": _("Are you sure you want to delete the status")
    }

task_manager/tasks/views.py
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from django.views.generic import ListView, DetailView

from task_manager.tasks.models import Task
from task_manager.tasks.forms import TaskForm

from task_manager.views import (CustomCreateView,
                               CustomUpdateView,
                               CustomDeleteView)
from task_manager.mixins import (CustomLoginMixin,
                                 CustomUserPassesTestMixin)


class TaskListView(CustomLoginMixin, ListView):
    model = Task
    template_name =  'tasks/index.html'
    context_object_name = 'tasks'


class TaskCreateView(CustomCreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('tasks:index')
    success_message = _("Task successfully created")
    extra_context = {
        "button_name": _("Create"),
        "header": _("Create a task")
    }

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

class TaskUpdateView(CustomUpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy('tasks:index')
    success_message = _("Task successfully updated")
    extra_context = {
        "button_name": _("Update"),
        "header": _("Update task")
    }

class TaskDetailView(CustomLoginMixin, DetailView):
    template_name = 'tasks/task_detail.html'
    model = Task

class TaskDeleteView(CustomUserPassesTestMixin, CustomDeleteView):
    model = Task
    success_url = reverse_lazy('tasks:index')
    success_message = _('Task successfully deleted')
    permission_denied_url = reverse_lazy('tasks:index')
    permission_denied_message = _("A task can only be deleted by its author.")
    context_object_name = 'task'
    extra_context = {
        "title": _("Task deletion"),
        "confirmation": _("Are you sure you want to delete the task")
    }

    def test_func(self):
        return self.request.user == self.get_object().author

task_manager/users/views.py
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView, CreateView
from django.contrib.messages.views import SuccessMessageMixin

from task_manager.users.forms import SignUpForm
from task_manager.users.models import User

from task_manager.views import (CustomUpdateView,
                               CustomDeleteView)
from task_manager.mixins import CustomUserPassesTestMixin


class UserListView(ListView):
    model = User
    template_name = 'users/index.html'
    context_object_name = 'users'

class SignUp(SuccessMessageMixin, CreateView):
    model = User
    form_class = SignUpForm
    template_name = 'create_update_form.html'
    success_url = reverse_lazy('login')
    success_message = _("User registered successfully")
    extra_context = {
        "button_name": _("Register"),
        "header": _("Registration")
    }

class UserUpdateView(CustomUserPassesTestMixin, CustomUpdateView):
    model = User
    form_class = SignUpForm
    success_url = reverse_lazy('users:index')
    success_message = _("User successfully changed")
    permission_denied_url = reverse_lazy('users:index')
    permission_denied_message = _("You do not have permission to modify another user.")
    extra_context = {
        "button_name": _("Update"),
        "header": _("Update user")
    }

    def test_func(self):
        return self.request.user == self.get_object()

class UserDeleteView(CustomUserPassesTestMixin, CustomDeleteView):
    model = User
    success_url = reverse_lazy('users:index')
    success_message = _('User successfully deleted')
    permission_denied_url = reverse_lazy('users:index')
    permission_denied_message = _("You do not have permission to modify another user.")
    protected_message = _("Cannot delete user because it is in use")
    protected_url = reverse_lazy('users:index')
    context_object_name = 'user'
    extra_context = {
        "title": _("User deletion"),
        "confirmation": _("Are you sure you want to delete")
    }

    def test_func(self):
        return self.request.user == self.get_object()

task_manager/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import AuthenticationForm

from django.utils.translation import gettext_lazy as _
from django.shortcuts import redirect
from django.contrib.auth import logout
from django.contrib import messages
from django.urls import reverse_lazy
from django.db.models import ProtectedError

from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView, UpdateView, DeleteView

from task_manager.mixins import CustomLoginMixin, CustomSingleObjectMixin



class HomePageView(TemplateView):
    template_name = "home.html"


class LoginUser(SuccessMessageMixin, LoginView):
    template_name = 'create_update_form.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('home')
    success_message = _('You are logged in')
    extra_context = {
        'header': _('Log In'),
        'button_name': _('Login'),
    }


class Logout(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        messages.success(request, _("You are logged out"))
        logout(request)
        return redirect('home')

class CustomCreateView(CustomLoginMixin, SuccessMessageMixin, CreateView):  #replace
    template_name = 'create_update_form.html'


class CustomUpdateView(CustomLoginMixin, SuccessMessageMixin, UpdateView):
    template_name = 'create_update_form.html'


class CustomDeleteView(CustomLoginMixin,
                       CustomSingleObjectMixin,
                       SuccessMessageMixin,
                       DeleteView):
    template_name = 'delete_form.html'
    protected_message = None
    protected_url = None

    def post(self, request, *args, **kwargs):
        try:
            return super().post(request, *args, **kwargs)
        except ProtectedError:
            messages.error(request, self.protected_message)
            return redirect(self.protected_url)

task_manager/templates/tasks/index.html
{% extends "base.html" %}

{% load i18n %}
{% block content %}
<div class="container wrapper flex-grow-1">
    <h1 class="my-4">{% trans "Tasks" %}</h1>
    <a class="btn btn-primary mb-3" href="/tasks/create/" role="button">{% trans "Create a task" %}</a>
    <div class="card mb-3">
        <div class="card-body bg-light">
    <form class="form-inline center" method="get">
      {% csrf_token %}
      <div class="mb-3">
        <label class="form-label" for="id_status">{% trans "Status" %}</label>
        <select name="status" class="form-select ml-2 mr-3" id="id_status">
          <option value="" selected="">---------</option>
          {% for status in statuses %}
          <option value="{{ status.id }}">{{ status }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="mb-3">
        <label class="form-label" for="id_executor">{% trans "Executor" %}</label>
        <select name="executor" class="form-select ml-2 mr-3" id="id_executor">
          <option value="" selected="">---------</option>
          {% for executor in executors %}
          <option value="{{ executor.id }}">{{ executor.username }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="mb-3">
        <label class="form-label" for="id_labels">{% trans "Label" %}</label>
        <select name="executor" class="form-select ml-2 mr-3" id="id_labels">
          <option value="" selected="">---------</option>
          {% for label in labels %}
          <option value="{{ label.id }}">{{ label }}</option>
          {% endfor %}
        </select>
      </div>
      <div class="mb-3">
        <div class="form-check">
          <input type="checkbox" name="self_tasks" class="form-check-input mr-3" id="id_self_tasks">
          <label class="form-check-label" for="id_self_tasks">{% trans "Only your tasks" %}</label>
        </div></div>
        <input class="btn btn-primary" type="submit" value={% trans "Show" %}>
    </form>
  </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>{% trans "Name" %}</th>
      <th>{% trans "Status" %}</th>
      <th>{% trans "Author" %}</th>
      <th>{% trans "Executor" %}</th>
      <th>{% trans "Date of creation" %}</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  {% for task in tasks %}
    <tr>
      <td>{{ task.id }}</td>
      <td><a href="{% url 'tasks:detail' pk=task.id %}">{{ task }}</a></td>
      <td>{{ task.status }}</td>
      <td>{{ task.author }}</td>
      <td>{{ task.executor }}</td>
      <td>{{ task.created_at }}</td>
      <td>
        <a href="{% url 'tasks:update' pk=task.id %}">{% trans "Change" %}</a>
        <br>
        <a href="{% url 'tasks:delete' pk=task.id %}">{% trans "Delete" %}</a>
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
</div>
{% endblock %}

task_manager/templates/tasks/status_delete_form.html
{% extends "base.html" %}


{% block content %}
<div class="container wrapper flex-grow-1">
    <h1 class="my-4">Удаление статуса</h1>
    <p>Вы уверены, что хотите удалить {{ status.name }}?</p>
    <form action="{% url 'statuses:delete' pk=status.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="Да, удалить">
    </form>
</div>
{% endblock %}

task_manager/templates/tasks/status_update_form.html
{% extends "base.html" %}


{% if form.errors %}
<div>
    <ul>
    {% for error in form.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ul>
</div>
{% endif %}

{% block content %}
<div class="container wrapper flex-grow-1">
    <h1 class="my-4">Изменение статуса</h1>
    <form action="{% url 'statuses:update' pk=status.pk %}" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label" for="id_name">Имя</label>
            <input type="text" name="name" value="{{ status.name }}" maxlength="100" class="form-control" placeholder="Имя" required="" id="id_name">
        </div>
        <input class="btn btn-primary" type="submit" value="Изменить">
    </form>
</div>
{% endblock %}

task_manager/templates/tasks/task_detail.html
{% extends "base.html" %}

{% load i18n %}
{% block content %}
<div class="container wrapper flex-grow-1">
  <h1 class="my-4">{% trans "View task" %}</h1>
  <div class="card">
    <div class="card-header bg-secondary text-white">
      <h2>{{ task.author }}</h2>
    </div>
  </div>
  <div class="card-body bg-light">
    <p>{{ task.description }}</p>
    <hr>
    <div class="container">
      <div class="row p-1">
        <div class="col">{% trans "Author" %}</div>
        <div class="col">{{ task.author }}</div>
      </div>
      <div class="row p-1">
        <div class="col">{% trans "Executor" %}</div>
        <div class="col">{{ task.executor }}</div>
      </div>
      <div class="row p-1">
        <div class="col">{% trans "Status" %}</div>
        <div class="col">{{ task.status }}</div>
      </div>
      <div class="row p-1">
        <div class="col">{% trans "Date of creation" %}</div>
        <div class="col">{{ task.created_at }}</div>
      </div>
      <div class="row p-1">
        <div class="col">
          <h6>{% trans "Labels" %}:</h6>
          <ul>
            {% for label in task.labels.all %}
            <li>{{ label }}</li>
            {% endfor %}
          </ul>
        </div>
      </div>
      <div class="row p-1">
        <div class="col">
          <a href="{% url 'tasks:update' task.id %}">{% trans "Update" %}</a>
          <br>
          <a href="{% url 'tasks:delete' task.id %}">{% trans "Delete" %}</a>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}